version: '2'

networks:
  basic:

services:
  ca.example.com:
    image: hyperledger/fabric-ca
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    container_name: ca.example.com
    ports: 
      - 7054:7054
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/7426d1ea5ea0bcebafa85d2d93cbe2c8e972026da5e3bbb9a1551e060cb4632b_sk
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - basic

  orderer.ordererorg.example.com:
    container_name: orderer.ordererorg.example.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrg
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/ordererorg.example.com/orderers/orderer.ordererorg.example.com/:/etc/hyperledger/msp/orderer
    networks:
      - basic

  chaincode.helper.example.com:
    container_name: chaincode.helper.example.com
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GODEBUG=netdns=go
      - CORE_CHAINCODE_LOGLEVEL=debug
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
    working_dir: /opt/gopath/src/github.com
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode_learning_go/chaincode/
        - ./crypto-config/peerOrganizations/:/opt/gopath/
        - ./../../golang:/opt/gopath/src/github.com/golang
    networks:
        - basic