// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tokenservice-resp.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingResponse struct {
	CommonResponse       *CommonResponse `protobuf:"bytes,1,opt,name=CommonResponse,proto3" json:"CommonResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_568a35d146945631, []int{0}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetCommonResponse() *CommonResponse {
	if m != nil {
		return m.CommonResponse
	}
	return nil
}

type CreateTokenResponse struct {
	CommonResponse       *CommonResponse `protobuf:"bytes,1,opt,name=CommonResponse,proto3" json:"CommonResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateTokenResponse) Reset()         { *m = CreateTokenResponse{} }
func (m *CreateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTokenResponse) ProtoMessage()    {}
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_568a35d146945631, []int{1}
}

func (m *CreateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTokenResponse.Unmarshal(m, b)
}
func (m *CreateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTokenResponse.Marshal(b, m, deterministic)
}
func (m *CreateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTokenResponse.Merge(m, src)
}
func (m *CreateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTokenResponse.Size(m)
}
func (m *CreateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTokenResponse proto.InternalMessageInfo

func (m *CreateTokenResponse) GetCommonResponse() *CommonResponse {
	if m != nil {
		return m.CommonResponse
	}
	return nil
}

type IssueTokenResponse struct {
	CommonResponse       *CommonResponse `protobuf:"bytes,1,opt,name=CommonResponse,proto3" json:"CommonResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *IssueTokenResponse) Reset()         { *m = IssueTokenResponse{} }
func (m *IssueTokenResponse) String() string { return proto.CompactTextString(m) }
func (*IssueTokenResponse) ProtoMessage()    {}
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_568a35d146945631, []int{2}
}

func (m *IssueTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueTokenResponse.Unmarshal(m, b)
}
func (m *IssueTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueTokenResponse.Marshal(b, m, deterministic)
}
func (m *IssueTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueTokenResponse.Merge(m, src)
}
func (m *IssueTokenResponse) XXX_Size() int {
	return xxx_messageInfo_IssueTokenResponse.Size(m)
}
func (m *IssueTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IssueTokenResponse proto.InternalMessageInfo

func (m *IssueTokenResponse) GetCommonResponse() *CommonResponse {
	if m != nil {
		return m.CommonResponse
	}
	return nil
}

type TransferTokenResponse struct {
	CommonResponse       *CommonResponse `protobuf:"bytes,1,opt,name=CommonResponse,proto3" json:"CommonResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TransferTokenResponse) Reset()         { *m = TransferTokenResponse{} }
func (m *TransferTokenResponse) String() string { return proto.CompactTextString(m) }
func (*TransferTokenResponse) ProtoMessage()    {}
func (*TransferTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_568a35d146945631, []int{3}
}

func (m *TransferTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferTokenResponse.Unmarshal(m, b)
}
func (m *TransferTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferTokenResponse.Marshal(b, m, deterministic)
}
func (m *TransferTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferTokenResponse.Merge(m, src)
}
func (m *TransferTokenResponse) XXX_Size() int {
	return xxx_messageInfo_TransferTokenResponse.Size(m)
}
func (m *TransferTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransferTokenResponse proto.InternalMessageInfo

func (m *TransferTokenResponse) GetCommonResponse() *CommonResponse {
	if m != nil {
		return m.CommonResponse
	}
	return nil
}

type GetTokenResponse struct {
	CommonResponse       *CommonResponse `protobuf:"bytes,1,opt,name=CommonResponse,proto3" json:"CommonResponse,omitempty"`
	Result               *TokenBalancePB `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_568a35d146945631, []int{4}
}

func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(m, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetCommonResponse() *CommonResponse {
	if m != nil {
		return m.CommonResponse
	}
	return nil
}

func (m *GetTokenResponse) GetResult() *TokenBalancePB {
	if m != nil {
		return m.Result
	}
	return nil
}

type PaginateTokenByUserNameResponse struct {
	CommonResponse       *CommonResponse   `protobuf:"bytes,1,opt,name=CommonResponse,proto3" json:"CommonResponse,omitempty"`
	PageSize             int32             `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	BookMark             string            `protobuf:"bytes,3,opt,name=BookMark,proto3" json:"BookMark,omitempty"`
	Results              []*TokenBalancePB `protobuf:"bytes,4,rep,name=Results,proto3" json:"Results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PaginateTokenByUserNameResponse) Reset()         { *m = PaginateTokenByUserNameResponse{} }
func (m *PaginateTokenByUserNameResponse) String() string { return proto.CompactTextString(m) }
func (*PaginateTokenByUserNameResponse) ProtoMessage()    {}
func (*PaginateTokenByUserNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_568a35d146945631, []int{5}
}

func (m *PaginateTokenByUserNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginateTokenByUserNameResponse.Unmarshal(m, b)
}
func (m *PaginateTokenByUserNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginateTokenByUserNameResponse.Marshal(b, m, deterministic)
}
func (m *PaginateTokenByUserNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginateTokenByUserNameResponse.Merge(m, src)
}
func (m *PaginateTokenByUserNameResponse) XXX_Size() int {
	return xxx_messageInfo_PaginateTokenByUserNameResponse.Size(m)
}
func (m *PaginateTokenByUserNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginateTokenByUserNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaginateTokenByUserNameResponse proto.InternalMessageInfo

func (m *PaginateTokenByUserNameResponse) GetCommonResponse() *CommonResponse {
	if m != nil {
		return m.CommonResponse
	}
	return nil
}

func (m *PaginateTokenByUserNameResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PaginateTokenByUserNameResponse) GetBookMark() string {
	if m != nil {
		return m.BookMark
	}
	return ""
}

func (m *PaginateTokenByUserNameResponse) GetResults() []*TokenBalancePB {
	if m != nil {
		return m.Results
	}
	return nil
}

type PaginateTokenByTokenNameResponse struct {
	CommonResponse       *CommonResponse   `protobuf:"bytes,1,opt,name=CommonResponse,proto3" json:"CommonResponse,omitempty"`
	PageSize             int32             `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	BookMark             string            `protobuf:"bytes,3,opt,name=BookMark,proto3" json:"BookMark,omitempty"`
	Results              []*TokenBalancePB `protobuf:"bytes,4,rep,name=Results,proto3" json:"Results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PaginateTokenByTokenNameResponse) Reset()         { *m = PaginateTokenByTokenNameResponse{} }
func (m *PaginateTokenByTokenNameResponse) String() string { return proto.CompactTextString(m) }
func (*PaginateTokenByTokenNameResponse) ProtoMessage()    {}
func (*PaginateTokenByTokenNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_568a35d146945631, []int{6}
}

func (m *PaginateTokenByTokenNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginateTokenByTokenNameResponse.Unmarshal(m, b)
}
func (m *PaginateTokenByTokenNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginateTokenByTokenNameResponse.Marshal(b, m, deterministic)
}
func (m *PaginateTokenByTokenNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginateTokenByTokenNameResponse.Merge(m, src)
}
func (m *PaginateTokenByTokenNameResponse) XXX_Size() int {
	return xxx_messageInfo_PaginateTokenByTokenNameResponse.Size(m)
}
func (m *PaginateTokenByTokenNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginateTokenByTokenNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaginateTokenByTokenNameResponse proto.InternalMessageInfo

func (m *PaginateTokenByTokenNameResponse) GetCommonResponse() *CommonResponse {
	if m != nil {
		return m.CommonResponse
	}
	return nil
}

func (m *PaginateTokenByTokenNameResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PaginateTokenByTokenNameResponse) GetBookMark() string {
	if m != nil {
		return m.BookMark
	}
	return ""
}

func (m *PaginateTokenByTokenNameResponse) GetResults() []*TokenBalancePB {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*PingResponse)(nil), "protos.PingResponse")
	proto.RegisterType((*CreateTokenResponse)(nil), "protos.CreateTokenResponse")
	proto.RegisterType((*IssueTokenResponse)(nil), "protos.IssueTokenResponse")
	proto.RegisterType((*TransferTokenResponse)(nil), "protos.TransferTokenResponse")
	proto.RegisterType((*GetTokenResponse)(nil), "protos.GetTokenResponse")
	proto.RegisterType((*PaginateTokenByUserNameResponse)(nil), "protos.PaginateTokenByUserNameResponse")
	proto.RegisterType((*PaginateTokenByTokenNameResponse)(nil), "protos.PaginateTokenByTokenNameResponse")
}

func init() { proto.RegisterFile("tokenservice-resp.proto", fileDescriptor_568a35d146945631) }

var fileDescriptor_568a35d146945631 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x53, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x65, 0xad, 0x56, 0x1d, 0x8b, 0xc8, 0x8a, 0x1a, 0x72, 0x31, 0xe4, 0xd4, 0x8b, 0x41, 0xf4,
	0xee, 0x21, 0x3d, 0x88, 0x07, 0x4b, 0x58, 0x53, 0x3c, 0x6f, 0xc3, 0x18, 0x42, 0x9a, 0xdd, 0xb0,
	0x93, 0x0a, 0x7a, 0xf4, 0xf7, 0xf4, 0xa3, 0xa4, 0xbb, 0xa6, 0xd0, 0x1e, 0x3c, 0xed, 0xa5, 0xa7,
	0x65, 0xde, 0xbc, 0x79, 0xf3, 0x1e, 0xc3, 0xc2, 0x55, 0xa7, 0x6b, 0x54, 0x84, 0xe6, 0xbd, 0x2a,
	0xf0, 0xc6, 0x20, 0xb5, 0x49, 0x6b, 0x74, 0xa7, 0xf9, 0xd0, 0x3e, 0x14, 0x8e, 0x0a, 0xdd, 0x34,
	0x5a, 0x39, 0x34, 0xe4, 0x96, 0x3e, 0x97, 0x0b, 0xa9, 0x0a, 0x74, 0x58, 0x3c, 0x85, 0x51, 0x56,
	0xa9, 0x52, 0x20, 0xb5, 0x5a, 0x11, 0xf2, 0x07, 0x38, 0x9d, 0xd8, 0x99, 0x1e, 0x09, 0x58, 0xc4,
	0xc6, 0x27, 0x77, 0x97, 0x8e, 0x4f, 0xc9, 0x66, 0x57, 0x6c, 0xb1, 0xe3, 0x19, 0x9c, 0x4f, 0x0c,
	0xca, 0x0e, 0xf3, 0xd5, 0x2e, 0x6f, 0xb2, 0x39, 0xf0, 0x27, 0xa2, 0xa5, 0x67, 0xd5, 0x57, 0xb8,
	0xc8, 0x8d, 0x54, 0xf4, 0x86, 0xc6, 0xaf, 0xf0, 0x17, 0x83, 0xb3, 0x47, 0xec, 0xbc, 0x8a, 0xf2,
	0x04, 0x86, 0x02, 0x69, 0xb9, 0xe8, 0x82, 0xbd, 0xcd, 0x39, 0xbb, 0x26, 0x75, 0x67, 0xcd, 0x52,
	0xf1, 0xc7, 0x8a, 0xbf, 0x19, 0x5c, 0x67, 0xb2, 0xac, 0x54, 0x7f, 0x8d, 0xf4, 0x63, 0x46, 0x68,
	0xa6, 0xb2, 0x41, 0x6f, 0x9e, 0x42, 0x38, 0xca, 0x64, 0x89, 0x2f, 0xd5, 0x27, 0x5a, 0x57, 0x07,
	0x62, 0x5d, 0xaf, 0x7a, 0xa9, 0xd6, 0xf5, 0xb3, 0x34, 0x75, 0x30, 0x88, 0xd8, 0xf8, 0x58, 0xac,
	0x6b, 0x7e, 0x0b, 0x87, 0xce, 0x25, 0x05, 0xfb, 0xd1, 0xe0, 0x9f, 0x30, 0x3d, 0x2d, 0xfe, 0x61,
	0x10, 0x6d, 0xa5, 0xb1, 0xcf, 0x6e, 0xc6, 0x99, 0xbb, 0x1f, 0x7a, 0xff, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0xc7, 0xa0, 0x0a, 0x48, 0xc3, 0x03, 0x00, 0x00,
}
