// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tokenlog.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenLogPB struct {
	TokenLogId           string   `protobuf:"bytes,1,opt,name=TokenLogId,proto3" json:"TokenLogId,omitempty"`
	FromUserName         string   `protobuf:"bytes,2,opt,name=FromUserName,proto3" json:"FromUserName,omitempty"`
	ToUserName           string   `protobuf:"bytes,3,opt,name=ToUserName,proto3" json:"ToUserName,omitempty"`
	TokenName            string   `protobuf:"bytes,4,opt,name=TokenName,proto3" json:"TokenName,omitempty"`
	TokenAmount          int64    `protobuf:"varint,5,opt,name=TokenAmount,proto3" json:"TokenAmount,omitempty"`
	Comment              string   `protobuf:"bytes,6,opt,name=Comment,proto3" json:"Comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenLogPB) Reset()         { *m = TokenLogPB{} }
func (m *TokenLogPB) String() string { return proto.CompactTextString(m) }
func (*TokenLogPB) ProtoMessage()    {}
func (*TokenLogPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_18151d9ffca8b24f, []int{0}
}

func (m *TokenLogPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenLogPB.Unmarshal(m, b)
}
func (m *TokenLogPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenLogPB.Marshal(b, m, deterministic)
}
func (m *TokenLogPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenLogPB.Merge(m, src)
}
func (m *TokenLogPB) XXX_Size() int {
	return xxx_messageInfo_TokenLogPB.Size(m)
}
func (m *TokenLogPB) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenLogPB.DiscardUnknown(m)
}

var xxx_messageInfo_TokenLogPB proto.InternalMessageInfo

func (m *TokenLogPB) GetTokenLogId() string {
	if m != nil {
		return m.TokenLogId
	}
	return ""
}

func (m *TokenLogPB) GetFromUserName() string {
	if m != nil {
		return m.FromUserName
	}
	return ""
}

func (m *TokenLogPB) GetToUserName() string {
	if m != nil {
		return m.ToUserName
	}
	return ""
}

func (m *TokenLogPB) GetTokenName() string {
	if m != nil {
		return m.TokenName
	}
	return ""
}

func (m *TokenLogPB) GetTokenAmount() int64 {
	if m != nil {
		return m.TokenAmount
	}
	return 0
}

func (m *TokenLogPB) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func init() {
	proto.RegisterType((*TokenLogPB)(nil), "protos.TokenLogPB")
}

func init() { proto.RegisterFile("tokenlog.proto", fileDescriptor_18151d9ffca8b24f) }

var fileDescriptor_18151d9ffca8b24f = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xc9, 0xcf, 0x4e,
	0xcd, 0xcb, 0xc9, 0x4f, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a,
	0xa7, 0x18, 0xb9, 0xb8, 0x42, 0x40, 0x52, 0x3e, 0xf9, 0xe9, 0x01, 0x4e, 0x42, 0x72, 0x08, 0x9e,
	0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x92, 0x88, 0x90, 0x12, 0x17, 0x8f, 0x5b,
	0x51, 0x7e, 0x6e, 0x68, 0x71, 0x6a, 0x91, 0x5f, 0x62, 0x6e, 0xaa, 0x04, 0x13, 0x58, 0x05, 0x8a,
	0x18, 0xc4, 0x0c, 0xb8, 0x0a, 0x66, 0x98, 0x19, 0x70, 0x79, 0x19, 0x2e, 0x4e, 0xb0, 0x89, 0x60,
	0x69, 0x16, 0xb0, 0x34, 0x42, 0x40, 0x48, 0x81, 0x8b, 0x1b, 0xcc, 0x71, 0xcc, 0xcd, 0x2f, 0xcd,
	0x2b, 0x91, 0x60, 0x55, 0x60, 0xd4, 0x60, 0x0e, 0x42, 0x16, 0x12, 0x92, 0xe0, 0x62, 0x77, 0xce,
	0xcf, 0xcd, 0x4d, 0xcd, 0x2b, 0x91, 0x60, 0x03, 0xeb, 0x86, 0x71, 0x93, 0x20, 0x9e, 0x32, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xea, 0x11, 0xb7, 0xb7, 0xed, 0x00, 0x00, 0x00,
}
